[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.18.0"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]

# Handle i18n redirects
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-handler"
  status = 200