[build]
  command = "CI=true npm install && CI=true next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.18.0"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  ESLINT_NO_DEV_ERRORS = "true"

[functions]
  included_files = [
    "node_modules/@netlify/plugin-nextjs/**/*",
    "node_modules/stripe/**/*",
    "node_modules/axios/**/*"
  ]

# Handle i18n redirects
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-handler"
  status = 200